version: '3'

services:
  proxy:
    env_file:
      - .env
    container_name: proxy
    image: 'lb-proxy'
    build:
      context: nginx/proxy
    ports:
      - "${PROXY_PORT}:80"
    restart: unless-stopped
    volumes:
      - "./nginx/proxy/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/proxy/logs/:/var/log/nginx"
    depends_on:
      - nginx-srv-1
      - nginx-srv-2
    networks:
      - proxy-lb

  nginx-srv-1:
    env_file:
      - .env
    container_name: nginx-srv-1
    image: 'lb-nginx-srv-1'
    build:
      context: ./nginx/nginx-srv-1
    ports:
      - "${SERVICE_1_PORT}:80"
    restart: unless-stopped
    depends_on:
      - php-srv-1
    volumes:
      - "./nginx/nginx-srv-1/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/nginx-srv-1/logs/:/var/log/nginx"
      - "./app:/var/www/html"
    networks:
      - proxy-lb

  nginx-srv-2:
    env_file:
      - .env
    container_name: nginx-srv-2
    image: 'lb-nginx-srv-2'
    build:
      context: ./nginx/nginx-srv-2
    ports:
      - "${SERVICE_2_PORT}}:80"
    restart: unless-stopped
    depends_on:
      - php-srv-2
    volumes:
      - "./nginx/nginx-srv-1/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/nginx-srv-2/logs/:/var/log/nginx"
      - "./app:/var/www/html"
    networks:
      - proxy-lb

  php-srv-1:
    container_name: php-srv-1
    image: 'php-srv-1'
    build:
      context: ./services/php-srv-1
    ports:
      - "${PHP_1_PORT}:9000"
    restart: unless-stopped
    volumes:
      - "./services/php-srv-1/php.ini:/usr/local/etc/php/conf.d/local.ini"
      - "./app:/var/www/html"

    networks:
      - proxy-lb
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-srv-2:
    container_name: php-srv-2
    image: 'php-srv-2'
    build:
      context: ./services/php-srv-2
    ports:
      - "${PHP_2_PORT}:9000"
    restart: unless-stopped
    volumes:
      - ./services/php-srv-2/php.ini:/usr/local/etc/php/conf.d/local.ini
      - "./app:/var/www/html"
    networks:
      - proxy-lb
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  proxy-lb:
    name: proxy-lb-network