version: '3'

services:
  proxy:
    container_name: proxy
    image: 'lb-proxy'
    build:
      context: ./proxy
    ports:
      - "80:80"
    volumes:
      - "./proxy/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - proxy-lb
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-srv-1:
    container_name: php-srv-1
    image: 'php-srv-1'
    build:
      context: ./services/php-srv-1
    volumes:
      - ./services/php-srv-1/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - proxy-lb
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php-srv-2:
    container_name: php-srv-2
    image: 'php-srv-2'
    build:
      context: ./services/php-srv-2
    volumes:
      - ./services/php-srv-2/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - proxy-lb
    extra_hosts:
      - "host.docker.internal:host-gateway"


networks:
  proxy-lb:
    name: proxy-lb-network